### ISSUE TITLE
Leute einladen

### ISSUE THREAD

**Issue by rubo77** [KreativHack/opendata#1]
kannst du uns mal alle in das opendata repo einladen als collaborators?

**Comment by dbanck** [comment]
Da ich nicht weiß, wer "ale" sind, bist du jetzt Owner in der Orga und kannst gerne selbst Member einladen und Repos anlegen.

**Comment by rubo77** [comment]
Ich habe keine rechte, wo hast du mich denn geadded? jhab keine nachricht bekommen
